# Generated by Django 2.2.5 on 2019-12-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=200)),
                ('h_desc', models.TextField()),
                ('h_image', models.FileField(blank=True, upload_to='homepage_image')),
            ],
        ),
    ]
