# Generated by Django 2.2.5 on 2019-12-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='h_icon',
            field=models.FileField(blank=True, upload_to='homepage_image'),
        ),
    ]
