# Generated by Django 2.2.5 on 2019-12-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homepage_h_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('s_desc', models.TextField()),
                ('s_image', models.FileField(blank=True, upload_to='skills_image')),
            ],
        ),
    ]
