# Generated by Django 2.2.5 on 2019-12-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skillset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=100)),
                ('l_desc', models.TextField()),
                ('l_image', models.FileField(blank=True, upload_to='learning_image')),
            ],
        ),
    ]
