# Generated by Django 2.2.5 on 2019-12-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_learning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100)),
                ('a_desc', models.TextField()),
                ('a_image', models.FileField(blank=True, upload_to='alternative_image')),
            ],
        ),
    ]
