# Generated by Django 2.2.5 on 2019-12-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alternative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Second_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_name', models.CharField(max_length=100)),
                ('sec_desc', models.TextField()),
                ('sec_image', models.FileField(blank=True, upload_to='second_image')),
            ],
        ),
    ]
