# Generated by Django 2.2.5 on 2019-12-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_second_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_desc', models.TextField()),
                ('p_image', models.FileField(blank=True, upload_to='project_image')),
            ],
        ),
    ]
