# Generated by Django 2.2.5 on 2019-12-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='p_url',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
